const ShopActionTypes = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTTIONS_FAILURE'
};

export default ShopActionTypes;
